package Form;


import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.Color;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Form.KoneksiDB;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Febrian Afandi
 */
public class Form_Nilai extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Kelas
     */
    public Form_Nilai() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).setNorthPane(null);
        ViewData();
        LebarKolom();
    }
    
    private void LebarKolom(){
        TableColumn column;
        tabel.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabel.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabel.getColumnModel().getColumn(2).setPreferredWidth(30);
        tabel.getColumnModel().getColumn(3).setPreferredWidth(30);
        tabel.getColumnModel().getColumn(4).setPreferredWidth(150);
        tabel.getColumnModel().getColumn(5).setPreferredWidth(150);
        tabel.getColumnModel().getColumn(6).setPreferredWidth(150);
        tabel.getColumnModel().getColumn(7).setPreferredWidth(150);
        tabel.getColumnModel().getColumn(8).setPreferredWidth(150);
        tabel.getColumnModel().getColumn(9).setPreferredWidth(150);
    }
    public void ViewData(){
        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("NIS Siswa");
        tbl.addColumn("Nama Kelas");
        tbl.addColumn("Semester");
        tbl.addColumn("Tahun Ajaran");
        tbl.addColumn("Nilai Spiritual");
        tbl.addColumn("Nilai Motorik");
        tbl.addColumn("Nilai Kognitif");
        tbl.addColumn("Nilai Sosialemosional");
        tbl.addColumn("Nilai Pencapaian Keseluruhan");
        tabel.setModel(tbl);
        LebarKolom();
        try {
            Statement statement = (Statement)KoneksiDB.getcoConnection().createStatement();
            ResultSet rs=statement.executeQuery("select * from tbl_nilaisiswa");
            while (rs.next()){
            tbl.addRow(new Object[]{
            rs.getString("no_penilaian"),
            rs.getString("nis_siswa"),
            rs.getString("nm_kelas"),
            rs.getString("semester"),
            rs.getString("tahun_pelajaran"),
            rs.getString("nilai_spiritual"),
            rs.getString("nilai_motorik"),
            rs.getString("nilai_kognitif"),
            rs.getString("nilai_sosialemosional"),
            rs.getString("nilai_tingkatpencapaiankeseluruhan"),
            });
            tabel.setModel(tbl);
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,"Gagal");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fkelas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        fkelas.setBackground(new java.awt.Color(153, 255, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/system.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel2.setText("Cari");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close-window2.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/report.png"))); // NOI18N
        jLabel1.setText("NILAI");

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login3.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title1", "Title2", "Title3", "Title4", "Title5", "Title6", "Title7", "Title8", "Title9", "Title10"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel4.setText("A : Amat Baik");

        jLabel5.setText("B : Baik");

        jLabel6.setText("C : Cukup");

        jLabel7.setText("D : Perlu Dilatih");

        jLabel8.setText("Keterangan Nilai");

        javax.swing.GroupLayout fkelasLayout = new javax.swing.GroupLayout(fkelas);
        fkelas.setLayout(fkelasLayout);
        fkelasLayout.setHorizontalGroup(
            fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fkelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fkelasLayout.createSequentialGroup()
                .addGap(704, 704, 704)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fkelasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(991, 991, 991)
                .addComponent(jLabel3))
            .addGroup(fkelasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fkelasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fkelasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fkelasLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fkelasLayout.setVerticalGroup(
            fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fkelasLayout.createSequentialGroup()
                .addGroup(fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fkelasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnRefresh)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
      DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("NIS Siswa");
        tbl.addColumn("Nama Kelas");
        tbl.addColumn("Semester");
        tbl.addColumn("Tahun Ajaran");
        tbl.addColumn("Nilai Spiritual");
        tbl.addColumn("Nilai Motorik");
        tbl.addColumn("Nilai Kognitif");
        tbl.addColumn("Nilai Sosialemosional");
        tbl.addColumn("Nilai Pencapaian Keseluruhan");
      tabel.setModel(tbl);
      try {
          Statement statement = (Statement)KoneksiDB.getcoConnection().createStatement();
          ResultSet rs = statement.executeQuery("select * from tbl_nilaisiswa where no_penilaian like '% "+txtCari.getText()+"%'");
          while(rs.next()) {
              int row = tabel.getSelectedRow();
              tbl.addRow (new Object[]{
            rs.getString("no_penilaian"),
            rs.getString("nis_siswa"),
            rs.getString("nm_kelas"),
            rs.getString("semester"),
            rs.getString("tahun_pelajaran"),
            rs.getString("nilai_spiritual"),
            rs.getString("nilai_motorik"),
            rs.getString("nilai_kognitif"),
            rs.getString("nilai_sosialemosional"),
            rs.getString("nilai_tingkatpencapaiankeseluruhan"),
              });
              tabel.setModel(tbl);
              LebarKolom();
          }
      }catch (Exception e){
}
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    ViewData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
          DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("NIS Siswa");
        tbl.addColumn("Nama Kelas");
        tbl.addColumn("Semester");
        tbl.addColumn("Tahun Ajaran");
        tbl.addColumn("Nilai Spiritual");
        tbl.addColumn("Nilai Motorik");
        tbl.addColumn("Nilai Kognitif");
        tbl.addColumn("Nilai Sosialemosional");
        tbl.addColumn("Nilai Pencapaian Keseluruhan");
      tabel.setModel(tbl);
      try {
          Statement statement = (Statement)KoneksiDB.getcoConnection().createStatement();
          ResultSet rs = statement.executeQuery("select * from tbl_nilaisiswa where no_penilaian like '% "+txtCari.getText()+"%'");
          while(rs.next()) {
              int row = tabel.getSelectedRow();
              tbl.addRow (new Object[]{
            rs.getString("no_penilaian"),
            rs.getString("nis_siswa"),
            rs.getString("nm_kelas"),
            rs.getString("semester"),
            rs.getString("tahun_pelajaran"),
            rs.getString("nilai_spiritual"),
            rs.getString("nilai_motorik"),
            rs.getString("nilai_kognitif"),
            rs.getString("nilai_sosialemosional"),
            rs.getString("nilai_tingkatpencapaiankeseluruhan"),
              });
              tabel.setModel(tbl);
              LebarKolom();
          }
      }catch (SQLException e){
}
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        Form_InputNilai nilai= new Form_InputNilai ((null), closable);
        nilai.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel fkelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
